name: math_helper
description: A Flutter package to create and calculate various geometric relationships on coordinate.
version: 0.0.2
repository: https://github.com/tony-kcl/math_helper

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter